-- AUTHORITATIVE PHASE 0A DISPOSABLE LEGACY BOOTSTRAP.
-- PROPOSED, DATA-FREE, UNEXECUTED. Never use in a linked database.
-- Required: set opps.phase0a_disposable_bootstrap='approved-local-only';
begin;
do $$ declare obj text; begin
  if current_setting('opps.phase0a_disposable_bootstrap',true) is distinct from 'approved-local-only'
    then raise exception 'Disposable bootstrap guard is not enabled.'; end if;
  foreach obj in array array['users','clients','projects','orders','suppliers','inventory','purchase_orders','transactions','active_orders','v_orders','v_purchase_orders'] loop
    if to_regclass('public.'||obj) is not null then
      raise exception 'Refusing non-empty schema: public.% already exists.',obj;
    end if;
  end loop;
end $$;
create extension if not exists pgcrypto;

create table public.users(id uuid primary key default gen_random_uuid(),auth_user_id uuid,user_email text,full_name text,role text not null default 'user',department text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.clients(id uuid primary key default gen_random_uuid(),name text not null,email text,phone text,status text default 'lead',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.projects(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete set null,name text not null,project_code text,status text default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.orders(
 id uuid primary key default gen_random_uuid(),client_name text not null,client_email text,client_phone text,order_number text not null unique,status text not null default 'confirmed',priority text not null default 'normal',products jsonb not null default '[]',total_amount numeric(12,2) not null default 0,deposit_paid numeric(12,2) not null default 0,print_type text,special_instructions text,notes text,due_date date,courier text,tracking_number text,file_urls jsonb not null default '[]',assigned_team jsonb not null default '[]',linked_po_id uuid,client_id uuid references public.clients(id) on delete set null,project_id uuid references public.projects(id) on delete set null,pipeline_stage text,is_archived boolean not null default false,archived_at timestamptz,archived_by text,source text not null default 'opps',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index idx_legacy_orders_status on public.orders(status,is_archived);
create index idx_legacy_orders_project_id on public.orders(project_id);

create table public.suppliers(
 id uuid primary key default gen_random_uuid(),name text not null,type text not null,location text,address text,contact_name text,contact_email text,contact_phone text,contacts jsonb not null default '[]',products jsonb not null default '[]',delivery_cost numeric(12,2),lead_time_days integer,payment_terms text,category text,notes text,is_preferred boolean not null default false,is_archived boolean not null default false,archived_at timestamptz,archived_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.inventory(
 id uuid primary key default gen_random_uuid(),name text not null,sku text,category text,current_stock numeric not null default 0,unit text not null default 'pieces',preferred_supplier_id uuid references public.suppliers(id) on delete set null,unit_cost numeric(12,2),location text,is_archived boolean not null default false,archived_at timestamptz,archived_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index idx_legacy_inventory_preferred_supplier on public.inventory(preferred_supplier_id);

-- Intentional overlap: later checked-in CREATE TABLE lacks confirmed Phase 0A columns.
create table public.purchase_orders(
 id uuid primary key default gen_random_uuid(),po_number text unique,supplier_ids uuid[] not null default '{}',supplier_id uuid references public.suppliers(id) on delete set null,supplier_name text,project_id uuid references public.projects(id) on delete set null,linked_order_id uuid references public.orders(id) on delete set null,status text not null default 'draft',items jsonb not null default '[]',notes text,subtotal numeric(12,2) not null default 0,tax numeric(12,2) not null default 0,total_amount numeric(12,2) not null default 0,total numeric(12,2) not null default 0,order_date date,expected_date date,expected_delivery date,received_date date,comments jsonb not null default '[]',is_archived boolean not null default false,archived_at timestamptz,archived_by text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index idx_legacy_purchase_orders_supplier_id on public.purchase_orders(supplier_id);
alter table public.orders add constraint orders_linked_po_legacy_fk foreign key(linked_po_id) references public.purchase_orders(id) on delete set null;

create table public.transactions(
 id uuid primary key default gen_random_uuid(),type text not null,amount numeric(12,2) not null default 0,description text,notes text,vendor text,approval_status text,payment_status text,payment_method text,expense_category text,client_id uuid references public.clients(id) on delete set null,project_id uuid references public.projects(id) on delete set null,order_id uuid references public.orders(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index idx_legacy_transactions_order_id on public.transactions(order_id);

-- Required before the lexically earlier finance RLS migration.
create table public.finance_budget_buckets(id uuid primary key default gen_random_uuid(),name text not null,category text,monthly_budget numeric default 0,used_amount numeric default 0,notes text,status text default 'active',created_by text,created_at timestamptz default now(),updated_at timestamptz default now(),archived_at timestamptz,archived_by text);
create table public.finance_buying_items(id uuid primary key default gen_random_uuid(),item_name text not null,category text,reason text,estimated_cost numeric default 0,priority text default 'medium',status text default 'idea',target_date date,budget_bucket_id uuid references public.finance_budget_buckets(id) on delete set null,notes text,added_by text,created_at timestamptz default now(),updated_at timestamptz default now(),archived_at timestamptz);
create table public.order_stages(key text primary key,display_name text not null,sequence integer not null default 0,is_exception boolean not null default false,color text,sla_hours integer,legacy_status text);
create table public.order_tags(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,role_key text not null,created_at timestamptz not null default now(),unique(order_id,role_key));
create table public.order_exceptions(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,exception_type text,notes text,created_at timestamptz not null default now());
create table public.order_stage_history(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,stage_key text,created_at timestamptz not null default now());
create table public.tasks(id uuid primary key default gen_random_uuid(),project_id uuid references public.projects(id) on delete set null,linked_order_id uuid references public.orders(id) on delete set null,client_id uuid references public.clients(id) on delete set null,title text,status text,created_at timestamptz not null default now());
create table public.ops_tasks(id uuid primary key default gen_random_uuid(),project_id uuid references public.projects(id) on delete set null,order_id uuid references public.orders(id) on delete set null,client_id uuid references public.clients(id) on delete set null,title text,status text,created_at timestamptz not null default now());
create table public.folders(id uuid primary key default gen_random_uuid(),parent_id uuid references public.folders(id) on delete set null,project_id uuid references public.projects(id) on delete set null,order_id uuid references public.orders(id) on delete set null,client_id uuid references public.clients(id) on delete set null,name text not null,created_at timestamptz not null default now());
create table public.client_assets(id uuid primary key default gen_random_uuid(),folder_id uuid references public.folders(id) on delete set null,project_id uuid references public.projects(id) on delete set null,order_id uuid references public.orders(id) on delete set null,client_id uuid references public.clients(id) on delete set null,file_url text,created_at timestamptz not null default now());
create table public.money_model_snapshots(id uuid primary key default gen_random_uuid(),snapshot jsonb not null default '{}',created_at timestamptz not null default now());

create table public.client_quote_requests(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete set null,client_email text,client_name text,project_name text,quantity text,deadline date,details text,source_app text,status text default 'new',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.client_messages(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete set null,client_email text,subject text,message text,sender_type text,is_internal boolean not null default false,order_id uuid references public.orders(id) on delete set null,xlab_order_id uuid,source_app text,status text default 'new',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.client_profile_requests(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete set null,client_email text,name text,phone text,company_name text,brand_name text,delivery_address text,source_app text,status text default 'pending_review',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.client_tech_pack_templates(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz not null default now());
create table public.client_tech_packs(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete cascade,template_id uuid references public.client_tech_pack_templates(id) on delete set null,title text,tech_pack_type text,status text default 'draft',source_app text,specs jsonb not null default '{}',approved_version_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.client_special_instructions(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete cascade,order_id uuid references public.orders(id) on delete set null,title text,instruction text,instruction_type text,visibility text,requires_approval boolean not null default false,approved_by_client boolean not null default false,approved_at timestamptz,status text default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.client_approvals(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete cascade,approval_type text,status text default 'pending',related_table text,related_id uuid,approved_by_name text,approved_by_email text,approved_at timestamptz,rejected_reason text,created_at timestamptz not null default now());
create table public.client_contract_templates(id uuid primary key default gen_random_uuid(),name text not null,contract_type text,version text,created_at timestamptz not null default now());
create table public.client_contract_acceptances(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id) on delete cascade,contract_template_id uuid references public.client_contract_templates(id) on delete set null,accepted_by_name text,accepted_by_email text,accepted_at timestamptz not null default now(),acceptance_method text,metadata jsonb not null default '{}',related_table text,related_id uuid);

create view public.active_orders as select o.id,o.client_name,o.client_email,o.client_phone,o.order_number,o.status,o.priority,o.products,o.total_amount,o.deposit_paid,o.print_type,o.special_instructions,o.notes,o.due_date,o.courier,o.tracking_number,o.file_urls,o.assigned_team,o.linked_po_id,o.is_archived,o.archived_at,o.archived_by,o.source,o.created_at,o.updated_at from public.orders o where o.is_archived=false;
create view public.v_orders as select o.id,o.client_name,o.client_email,o.client_phone,o.order_number,o.status,o.priority,o.products,o.total_amount,o.deposit_paid,o.print_type,o.special_instructions,o.notes,o.due_date,o.courier,o.tracking_number,o.file_urls,o.assigned_team,o.linked_po_id,o.is_archived,o.archived_at,o.archived_by,o.source,o.created_at,o.updated_at,o.client_id,o.project_id,c.name as client_display_name,c.status as client_status,p.name as project_name,p.project_code,po.po_number as linked_po_number,po.status as po_status from public.orders o left join public.clients c on o.client_id=c.id left join public.projects p on o.project_id=p.id left join public.purchase_orders po on o.linked_po_id=po.id;
create view public.v_purchase_orders as select po.id,po.po_number,po.supplier_ids,po.supplier_id,po.items,po.subtotal,po.tax,po.total,po.status,po.expected_delivery,po.notes,po.created_at,po.updated_at,s.name as supplier_name,s.location as supplier_location,s.type as supplier_type from public.purchase_orders po left join public.suppliers s on po.supplier_id=s.id where po.status<>all(array['archived'::text,'cancelled'::text]);
-- Intentional insecure legacy view state, isolated for revocation testing.
grant all privileges on table public.active_orders to anon,authenticated,service_role;
grant all privileges on table public.v_orders to anon,authenticated,service_role;
grant all privileges on table public.v_purchase_orders to anon,authenticated,service_role;
commit;


