import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function readSource(relativePath) {
  const raw = await readFile(new URL(`../${relativePath}`, import.meta.url), "utf8");
  return raw.replace(/\r\n/g, "\n");
}

const EDITOR = "src/components/orders/drawer/ProductsEditor.jsx";
const API = "src/api/xosClientProduct.js";
const LINE_CONFIG = "src/features/orders/lineConfiguration.js";
const INVOICE_MAPPER = "src/features/invoices/orderToInvoiceItems.js";

// ─────────────────────────────────────────────────────────────────────
// ORDERS CLIENT-PRODUCT REUSE — PHASE 1. One unified add flow: the
// existing Phase 0 client-product picker now routes through the
// canonical composed-add RPC + the EXISTING attach-composition resolver,
// instead of creating a plain commercial line with no setup fee.
// ─────────────────────────────────────────────────────────────────────

test("xosClientProduct.js: a minimal, self-contained wrapper - not built on the unmerged Phase C API surface (callRpc, createClientProductFromOrder)", async () => {
  const api = await readSource(API);
  assert.ok(api.includes('supabase.rpc("xos_add_composed_client_product_to_order"'));
  assert.ok(api.includes("idempotencyKey"), "the wrapper must require/pass an idempotency key");
  // strip comments first - the header explicitly names what it avoids
  // depending on, in prose, which would otherwise false-positive here.
  const functional = api.replace(/^\s*\/\/.*$/gm, "");
  assert.ok(!functional.includes("callRpc("), "must not depend on the unmerged Phase C callRpc helper");
  assert.ok(!functional.includes("createClientProductFromOrder"), "must not depend on unmerged Phase C exports");
});

test("the composed-add mutation generates the idempotency key ONCE per attempt and reuses it across retries", async () => {
  const src = await readSource(EDITOR);
  assert.ok(src.includes("const composedAddIdempotencyKeyRef = useRef"), "a ref, not state - must survive re-renders without triggering one, and must not be regenerated by parent-level rerenders");
  const mutationStart = src.indexOf("const addComposedClientProductMutation = useMutation({");
  const mutationEnd = src.indexOf("onError: (err) => toast.error(mapXosComposedAddError", mutationStart);
  const body = src.slice(mutationStart, mutationEnd);
  assert.ok(body.includes("if (!composedAddIdempotencyKeyRef.current) composedAddIdempotencyKeyRef.current = newLineId();"),
    "the key is only minted when absent - a retry of the same attempt reuses it, never mints a fresh one");
});

test("the idempotency key is cleared on success and on explicit Cancel - never left stale for the next unrelated add", async () => {
  const src = await readSource(EDITOR);
  const mutationStart = src.indexOf("const addComposedClientProductMutation = useMutation({");
  // Widened match: refresh-safe idempotency (a later phase) added a
  // `resumed` field to this same destructure.
  const onSuccessStart = src.indexOf("onSuccess: ({ replayed, setupLineCount, snapshotOutcome, resumed })", mutationStart);
  const onSuccessBody = src.slice(onSuccessStart, onSuccessStart + 200);
  assert.ok(onSuccessBody.includes('composedAddIdempotencyKeyRef.current = "";'), "cleared on success");
  assert.ok(src.includes('composedAddIdempotencyKeyRef.current = ""; setAddMode(false);'), "cleared on the Cancel button's click handler");
});

test("selecting a client product routes 'Add' through the composed-add mutation, not the plain addRow path", async () => {
  const src = await readSource(EDITOR);
  const handlerStart = src.indexOf("const handleAddRowClick = () => {");
  const handlerBody = src.slice(handlerStart, src.indexOf("};", handlerStart));
  assert.ok(handlerBody.includes('newRow.source === "client_product" && newRow.client_product_id'));
  assert.ok(handlerBody.includes("addComposedClientProductMutation.mutate("));
  assert.ok(handlerBody.includes("addRow();"), "every other source (catalog/stock/custom) still falls through to the unchanged addRow path");
});

test("the composed-add flow reuses resolveComposition + writeAttachSnapshots - the EXACT same functions beginAttach/confirmAttach use, never a second copy", async () => {
  const src = await readSource(EDITOR);
  // beginAttach must now delegate to resolveComposition, not inline the old logic
  const beginAttachStart = src.indexOf("const beginAttach = async (lineId, clientProductId, orderLine) => {");
  const beginAttachBody = src.slice(beginAttachStart, src.indexOf("\n  };", beginAttachStart));
  assert.ok(beginAttachBody.includes("await resolveComposition(lineId, clientProductId, orderLine)"));

  // confirmAttach must delegate to writeAttachSnapshots
  const confirmAttachStart = src.indexOf("const confirmAttach = useMutation({");
  const confirmAttachBody = src.slice(confirmAttachStart, confirmAttachStart + 200);
  assert.ok(confirmAttachBody.includes("writeAttachSnapshots(pendingResolution)"));

  // the composed-add mutation must call the SAME two functions, not reimplement them
  const composedStart = src.indexOf("const addComposedClientProductMutation = useMutation({");
  const composedBody = src.slice(composedStart, src.indexOf("onSuccess: ({ replayed", composedStart));
  assert.ok(composedBody.includes("await resolveComposition(parentLineId, clientProductId,"));
  assert.ok(composedBody.includes("await writeAttachSnapshots(result)"));
  assert.ok(!composedBody.includes("OrderLineComponentSnapshot.create("), "must not re-implement snapshot creation inline - only writeAttachSnapshots may call .create()");
});

test("an ambiguous/multiple-match resolution opens the SAME staff-review UI (pendingResolution), auto-confirm only happens when unblocked", async () => {
  const src = await readSource(EDITOR);
  const composedStart = src.indexOf("const addComposedClientProductMutation = useMutation({");
  const composedBody = src.slice(composedStart, src.indexOf("onSuccess: ({ replayed", composedStart));
  assert.ok(composedBody.includes("if (resolutionIsBlocked(result)) {"));
  assert.ok(composedBody.includes("setPendingResolution(result);"), "a blocked resolution surfaces the existing review UI, exactly like a manual attach");
});

test("a resolution/snapshot failure never rolls back or silently retries the already-created commercial lines", async () => {
  const src = await readSource(EDITOR);
  const composedStart = src.indexOf("const addComposedClientProductMutation = useMutation({");
  const composedBody = src.slice(composedStart, src.indexOf("onSuccess: ({ replayed", composedStart));
  assert.ok(/catch \(err\) \{[\s\S]*?toast\.error/.test(composedBody), "a caught failure is surfaced to staff");
  assert.ok(!/catch \(err\) \{[\s\S]*?mutate\(/.test(composedBody), "never auto-retries the add from inside the catch block");
});

test("+ Add print option is guarded against a canonical composed line at both the click handler and the mutation", async () => {
  const src = await readSource(EDITOR);
  const guardCondition = 'orderLine?.line_role === "setup_fee" || (orderLine?.line_role === "product" && orderLine?.price_breakdown?.mode === "composed")';
  const clickGuardCondition = 'p.line_role === "setup_fee" || (p.line_role === "product" && p?.price_breakdown?.mode === "composed")';
  assert.ok(src.includes(guardCondition), "addPrintOptionMutation guards on a composed line");
  assert.ok(src.includes(clickGuardCondition), "onStartAddPrintOption's click handler guards on a composed line too - defence in depth");
});

test("productLineTotal excludes a reserved 'breakdown' line; productQuantityTotal excludes any non-'product' role (setup_fee doesn't inflate the unit count)", async () => {
  const src = await readSource(EDITOR);
  const totalStart = src.indexOf("const productLineTotal = products.reduce((sum, raw) => {");
  const totalBody = src.slice(totalStart, src.indexOf("}, 0);", totalStart));
  assert.ok(totalBody.includes('if (product.line_role === "breakdown") return sum;'));

  const qtyStart = src.indexOf("const productQuantityTotal = products.reduce((sum, raw) => {");
  const qtyBody = src.slice(qtyStart, src.indexOf("}, 0);", qtyStart));
  assert.ok(qtyBody.includes('if (product.line_role && product.line_role !== "product") return sum;'));
});

test("lineConfiguration.js: a setup_fee/breakdown line is never production-capable, even though it carries client_product_id", async () => {
  const src = await readSource(LINE_CONFIG);
  const fnStart = src.indexOf("function hasProductionIdentity(product) {");
  const fnBody = src.slice(fnStart, src.indexOf("\n}", fnStart));
  assert.ok(fnBody.includes('if (product?.line_role && product.line_role !== "product") return false;'));
});

test("the invoice mapper already bills a setup_fee line correctly with zero changes needed (quantity is always 1 on that line, from the RPC)", async () => {
  // Read-only verification per Phase 1 §8 - this file is intentionally
  // untouched by this phase. itemFromProduct maps quantity/price per
  // line generically; since the RPC always sets quantity: 1 on a
  // setup_fee companion, no line_role-specific code is needed here for
  // this phase's shape (parent billed at qty x rate, setup fee billed
  // once). A hypothetical 'breakdown'-role line would currently still be
  // billed too - a latent, pre-existing gap this phase does not
  // introduce (nothing here emits that role) and does not fix, per the
  // explicit "do not touch invoice numbering" scope exclusion.
  const src = await readSource(INVOICE_MAPPER);
  assert.ok(!src.includes("line_role"), "confirms this phase made no invoice-mapper changes - the file is read-only verified, not modified");
});
