import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { dataClient } from "@/api/dataClient";
import { supabase } from "@/lib/supabaseClient";
import { isAdmin } from "@/lib/admin";
import { userDisplayName } from "@/lib/teamUsers";

export default function Directory() {
  const [tab, setTab] = useState("team"); const [me, setMe] = useState(null);
  useEffect(() => { dataClient.auth.me().then(setMe).catch(() => {}); }, []);
  const { data: team = [] } = useQuery({ queryKey: ["directory-team"], queryFn: () => dataClient.entities.User.list("name", 300) });
  const { data: clients = [] } = useQuery({ queryKey: ["directory-clients"], queryFn: () => dataClient.entities.Client.list("name", 300) });
  const { data: tenants = [] } = useQuery({ queryKey: ["directory-tenants"], enabled: isAdmin(me), queryFn: async () => { const { data, error } = await supabase.from("tenants").select("id, name, slug, created_at").order("name"); if (error) throw error; return data ?? []; } });
  const tabs = [{ id: "team", label: `Team (${team.length})` }, { id: "clients", label: `Clients (${clients.length})` }, ...(isAdmin(me) ? [{ id: "tenants", label: `Tenants (${tenants.length})` }] : [])];
  return <main className="min-h-screen bg-background"><div className="mx-auto max-w-5xl px-4 py-6"><header className="mb-6"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Directory</p><h1 className="mt-1 text-2xl font-bold">People & workspaces</h1><p className="mt-1 text-sm text-muted-foreground">Internal team members, customer records, and workspaces are kept separate.</p></header><div className="mb-5 flex gap-2 overflow-x-auto">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`rounded-xl px-3 py-2 text-sm font-semibold ${tab === item.id ? "bg-primary text-primary-foreground" : "bg-secondary text-muted-foreground"}`}>{item.label}</button>)}</div>{tab === "team" && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{team.filter((user) => user.is_active !== false).map((user) => <article key={user.id} className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-3">{user.avatar_url ? <img src={user.avatar_url} alt="" className="h-10 w-10 rounded-full object-cover" /> : <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 font-semibold text-primary">{userDisplayName(user).charAt(0)}</div>}<div className="min-w-0"><p className="truncate font-semibold">{userDisplayName(user)}</p><p className="truncate text-xs text-muted-foreground">{user.role || "team"} � {user.email}</p></div></div></article>)}</div>}{tab === "clients" && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{clients.map((client) => <article key={client.id} className="rounded-2xl border border-border bg-card p-4"><p className="font-semibold">{client.name || client.brand_name || "Unnamed client"}</p><p className="mt-1 text-xs text-muted-foreground">{client.email || client.phone || "No contact details"}</p><p className="mt-2 text-xs text-muted-foreground">Customer record</p></article>)}</div>}{tab === "tenants" && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{tenants.map((tenant) => <article key={tenant.id} className="rounded-2xl border border-border bg-card p-4"><p className="font-semibold">{tenant.name}</p><p className="mt-1 text-xs text-muted-foreground">{tenant.slug}</p><p className="mt-2 text-xs text-muted-foreground">Workspace</p></article>)}</div>}</div></main>;
}