import React, { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useSearchParams } from "react-router-dom";
import { supabase } from "@/lib/supabaseClient";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { ArrowLeft, MessageCircle, MoreHorizontal, X } from "lucide-react";
import { format } from "date-fns";
import { toast } from "sonner";

const DEPARTMENTS = ["support", "design", "production", "finance", "delivery", "admin"];
const LABEL = (value) => value ? value.replace(/_/g, " ").replace(/\b\w/g, (char) => char.toUpperCase()) : "Unassigned";

export default function MetaWhatsAppInboxV2() {
  const [params, setParams] = useSearchParams();
  const queryClient = useQueryClient();
  const [mobileThread, setMobileThread] = useState(false);
  const [actionsOpen, setActionsOpen] = useState(false);
  const [department, setDepartment] = useState("support");
  const [note, setNote] = useState("");
  const [draft, setDraft] = useState("");
  const role = params.get("role") || "all";
  const selectedId = params.get("conversation");
  const updateParams = (patch) => { const next = new URLSearchParams(params); Object.entries(patch).forEach(([key, value]) => value && value !== "all" ? next.set(key, value) : next.delete(key)); setParams(next, { replace: true }); };

  const conversationsQuery = useQuery({ queryKey: ["opps-conversations-v2"], enabled: !!supabase, queryFn: async () => {
    const { data, error } = await supabase.from("opps_conversations").select("id,tenant_id,display_name,phone,wa_id,assigned_department,status,unread_count,last_message_at,last_message_preview,linked_order_id,linked_client_id,opps_messages(id,direction,message_type,body,received_at,created_at,opps_message_intelligence(intent,risk_level,suggested_department,suggested_next_action))").eq("channel", "whatsapp").order("last_message_at", { ascending: false, nullsFirst: false }); if (error) throw error; return data ?? [];
  }});
  const conversations = conversationsQuery.data ?? [];
  const visible = useMemo(() => conversations.filter((item) => matchesRole(item, role)), [conversations, role]);
  const selected = conversations.find((item) => item.id === selectedId) || visible[0] || null;
  const messages = useMemo(() => [...(selected?.opps_messages || [])].sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime()), [selected]);
  const notesQuery = useQuery({ queryKey: ["opps-notes-v2", selected?.id], enabled: !!selected?.id && !!supabase, queryFn: async () => { const { data, error } = await supabase.from("opps_conversation_notes").select("id,note,created_at,created_by").eq("conversation_id", selected.id); if (error) throw error; return data ?? []; }});
  const eventsQuery = useQuery({ queryKey: ["opps-events-v2", selected?.id], enabled: !!selected?.id && !!supabase, queryFn: async () => { const { data, error } = await supabase.from("opps_conversation_events").select("id,event_type,body,actor_email,metadata,created_at").eq("conversation_id", selected.id).order("created_at"); if (error) throw error; return data ?? []; }});
  const notes = notesQuery.data ?? []; const events = eventsQuery.data ?? [];
  const timeline = useMemo(() => mergeTimeline(messages, notes, events), [messages, notes, events]);

  useEffect(() => { if (selected) setDepartment(selected.assigned_department || latest(selected)?.suggested_department || "support"); }, [selected?.id, selected?.assigned_department]);
  const refresh = async () => { await queryClient.invalidateQueries({ queryKey: ["opps-conversations-v2"] }); await queryClient.invalidateQueries({ queryKey: ["opps-notes-v2", selected?.id] }); await queryClient.invalidateQueries({ queryKey: ["opps-events-v2", selected?.id] }); };
  const event = async (event_type, body, metadata = {}) => { const { data: auth } = await supabase.auth.getUser(); const { error } = await supabase.from("opps_conversation_events").insert({ conversation_id: selected.id, tenant_id: selected.tenant_id, event_type, body, metadata, actor_user_id: auth.user?.id || null, actor_email: auth.user?.email || null }); if (error) throw error; };
  const mutation = useMutation({ mutationFn: async ({ patch, eventType, body }) => { const { error } = await supabase.from("opps_conversations").update(patch).eq("id", selected.id); if (error) throw error; if (eventType) await event(eventType, body, patch); }, onSuccess: () => { toast.success("Conversation saved"); refresh(); }, onError: (error) => toast.error(error?.message || "Could not save conversation") });
  const noteMutation = useMutation({ mutationFn: async () => { const { data: auth } = await supabase.auth.getUser(); const { error } = await supabase.from("opps_conversation_notes").insert({ conversation_id: selected.id, tenant_id: selected.tenant_id, note_type: "internal", note, created_by: auth.user?.id || null }); if (error) throw error; }, onSuccess: () => { setNote(""); toast.success("Internal note saved"); refresh(); }, onError: (error) => toast.error(error?.message || "Could not save internal note") });
  const draftMutation = useMutation({ mutationFn: () => event("draft_reply", draft, { internal_only: true, delivery_status: "not_sent" }), onSuccess: () => { setDraft(""); toast.success("Draft saved internally — not sent"); refresh(); }, onError: (error) => toast.error(error?.message || "Could not save draft") });
  if (!supabase) return <div className="p-6">Supabase is not configured.</div>;

  const choose = (id) => { updateParams({ conversation: id }); setMobileThread(true); };
  return <div className="min-h-screen bg-slate-50 p-3 md:p-5"><div className="mx-auto max-w-[1600px]"><header className="mb-3 rounded-2xl bg-slate-950 p-4 text-white"><div className="flex items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-emerald-300">Meta WhatsApp · Phase 1</p><h1 className="text-xl font-bold">Operational Inbox</h1></div><Badge className="bg-white/10">Sending disabled</Badge></div><div className="mt-3 flex gap-2 overflow-x-auto"><Button size="sm" variant="secondary" onClick={() => updateParams({ role: "all" })}>All</Button>{DEPARTMENTS.map((item) => <Button key={item} size="sm" variant={role === item ? "default" : "secondary"} onClick={() => updateParams({ role: item })}>{LABEL(item)}</Button>)}<Button size="sm" variant={role === "team_logs" ? "default" : "secondary"} onClick={() => updateParams({ role: "team_logs" })}>Team logs</Button></div></header>
  <main className="grid gap-3 xl:grid-cols-[360px_minmax(0,1fr)_300px]"><aside className={`rounded-2xl border bg-white p-3 ${mobileThread ? "hidden md:block" : ""}`}><Input placeholder="Search chats" value={params.get("q") || ""} onChange={(e) => updateParams({ q: e.target.value })} className="mb-2" />{visible.filter((item) => !params.get("q") || `${item.display_name} ${item.phone} ${item.last_message_preview}`.toLowerCase().includes(params.get("q").toLowerCase())).map((item) => <button key={item.id} onClick={() => choose(item.id)} className={`mb-2 w-full rounded-xl border p-3 text-left ${selected?.id === item.id ? "border-emerald-400 bg-emerald-50" : "border-slate-100"}`}><div className="flex justify-between gap-2"><b className="truncate">{item.display_name || item.phone || "WhatsApp chat"}</b><span className="text-xs text-slate-500">{item.last_message_at && format(new Date(item.last_message_at), "HH:mm")}</span></div><p className="mt-1 truncate text-sm text-slate-500">{item.last_message_preview || "No preview"}</p><div className="mt-2 flex gap-1">{item.unread_count > 0 && <Badge>Unread {item.unread_count}</Badge>}<Badge variant="outline">{LABEL(item.assigned_department || latest(item)?.suggested_department)}</Badge></div></button>)}</aside>
  <section className={`min-h-[70vh] rounded-2xl border bg-white p-3 md:p-4 ${!mobileThread ? "hidden md:flex md:flex-col" : "flex flex-col"}`}>{selected ? <><div className="flex items-center justify-between border-b pb-3"><div className="flex items-center gap-2"><Button className="md:hidden" variant="ghost" size="icon" onClick={() => setMobileThread(false)}><ArrowLeft className="h-4 w-4" /></Button><div><b>{selected.display_name || selected.phone || "Conversation"}</b><p className="text-xs text-slate-500">{selected.status} · {LABEL(selected.assigned_department)}</p></div></div><Button variant="outline" size="sm" onClick={() => setActionsOpen(true)}><MoreHorizontal className="mr-1 h-4 w-4" />Actions</Button></div><div className="flex-1 space-y-3 overflow-y-auto py-4">{timeline.map((item) => <TimelineItem key={item.key} item={item} />)}{timeline.length === 0 && <p className="text-center text-sm text-slate-500">No conversation activity yet.</p>}</div><div className="border-t pt-3"><label className="text-sm font-semibold">Internal draft reply</label><Textarea value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Write a private draft only. It will not be sent to WhatsApp." className="mt-2 min-h-[80px]" /><div className="mt-2 flex items-center justify-between"><span className="text-xs text-slate-500">Draft only · Not sent</span><Button disabled={!draft.trim() || draftMutation.isPending} onClick={() => draftMutation.mutate()}>Save draft internally</Button></div></div></> : <p className="m-auto text-slate-500">Select a chat to view messages.</p>}</section>
  <aside className="hidden rounded-2xl border bg-white p-4 xl:block"><h2 className="font-semibold">OPPS context</h2><p className="mt-2 text-sm">Assigned: {LABEL(selected?.assigned_department)}</p><p className="text-sm">Status: {selected?.status || "—"}</p><p className="mt-3 text-xs text-slate-500">Reply sending disabled in Phase 1</p></aside></main>
  {actionsOpen && selected && <div className="fixed inset-0 z-50 flex items-end bg-black/40 p-3 md:items-center md:justify-center"><div className="max-h-[90vh] w-full max-w-md overflow-y-auto rounded-2xl bg-white p-4"><div className="flex justify-between"><h2 className="font-semibold">Conversation actions</h2><Button variant="ghost" size="icon" onClick={() => setActionsOpen(false)}><X /></Button></div><div className="mt-4 grid grid-cols-2 gap-2"><Button onClick={() => mutation.mutate({ patch: { unread_count: 0 }, eventType: "read_event", body: "Marked as read" })}>Mark as read</Button><Button variant="outline" onClick={() => mutation.mutate({ patch: { status: selected.status === "closed" ? "open" : "closed" }, eventType: "status_event", body: selected.status === "closed" ? "Conversation reopened" : "Conversation closed" })}>{selected.status === "closed" ? "Reopen" : "Close"}</Button></div><div className="mt-4 rounded-xl bg-slate-50 p-3"><label className="text-sm font-medium">Assign department</label><Select value={department} onValueChange={setDepartment}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent>{DEPARTMENTS.map((item) => <SelectItem key={item} value={item}>{LABEL(item)}</SelectItem>)}</SelectContent></Select><Button className="mt-2 w-full" onClick={() => mutation.mutate({ patch: { assigned_department: department }, eventType: "assignment_event", body: `Assigned to ${LABEL(department)}` })}>Save assignment</Button><div className="mt-2 grid grid-cols-2 gap-1">{DEPARTMENTS.map((item) => <Button key={item} variant="outline" size="sm" onClick={() => { setDepartment(item); mutation.mutate({ patch: { assigned_department: item }, eventType: "assignment_event", body: `Assigned to ${LABEL(item)}` }); }}>Assign {LABEL(item)}</Button>)}</div></div><div className="mt-4"><label className="text-sm font-medium">Internal note</label><Textarea value={note} onChange={(e) => setNote(e.target.value)} className="mt-2" placeholder="Internal coordination note…" /><Button className="mt-2 w-full" disabled={!note.trim() || noteMutation.isPending} onClick={() => noteMutation.mutate()}>Add internal note</Button></div></div></div>}</div></div>;
}

function latest(conversation) { return [...(conversation?.opps_messages || [])].sort((a, b) => new Date(b.created_at) - new Date(a.created_at))[0]?.opps_message_intelligence?.[0]; }
function matchesRole(conversation, role) { if (role === "all") return true; const intelligence = latest(conversation); if (role === "team_logs") return intelligence?.intent === "team_log"; return conversation.assigned_department === role || intelligence?.suggested_department === role || ({ support: ["general_support", "quote_request", "complaint", "unknown"], design: ["artwork_request", "design_update"], production: ["production_update", "order_update"], finance: ["invoice_request", "payment_query"], delivery: ["delivery_request"] }[role] || []).includes(intelligence?.intent); }
function mergeTimeline(messages, notes, events) { return [...messages.map((message) => ({ key: `m-${message.id}`, type: "whatsapp_inbound", body: message.body || message.message_type || "WhatsApp update", at: message.received_at || message.created_at, intelligence: message.opps_message_intelligence?.[0] })), ...notes.map((note) => ({ key: `n-${note.id}`, type: "internal_note", body: note.note, at: note.created_at })), ...events.map((event) => ({ key: `e-${event.id}`, type: event.event_type, body: event.body, at: event.created_at, actor: event.actor_email }))].sort((a, b) => new Date(a.at) - new Date(b.at)); }
function TimelineItem({ item }) { const time = item.at ? format(new Date(item.at), "d MMM · HH:mm") : "Now"; if (["system_event", "assignment_event", "status_event", "link_event", "read_event"].includes(item.type)) return <div className="text-center text-xs text-slate-500"><span className="rounded-full bg-slate-100 px-3 py-1">{item.body} · {time}</span></div>; if (item.type === "draft_reply") return <div className="ml-auto max-w-[86%] rounded-2xl rounded-br-sm bg-emerald-600 p-3 text-sm text-white"><p className="text-xs font-semibold text-emerald-100">Joint X draft</p><p className="mt-1 whitespace-pre-wrap">{item.body}</p><p className="mt-2 text-[11px] text-emerald-100">Draft only · Not sent · {time}</p></div>; if (item.type === "internal_note") return <div className="max-w-[88%] rounded-2xl rounded-bl-sm bg-slate-100 p-3 text-sm text-slate-800"><p className="text-xs font-semibold text-slate-500">Internal note</p><p className="mt-1 whitespace-pre-wrap">{item.body}</p><p className="mt-2 text-[11px] text-slate-500">{time}</p></div>; return <div className="max-w-[88%] rounded-2xl rounded-bl-sm bg-emerald-50 p-3 text-sm text-slate-900"><p className="whitespace-pre-wrap">{item.body}</p><div className="mt-2 flex items-center gap-2 text-[11px] text-slate-500"><span>{time}</span>{item.intelligence?.risk_level === "high" && <Badge variant="destructive">High risk</Badge>}</div></div>; }
