import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { differenceInDays, formatDistanceToNow } from "date-fns";
import { supabase } from "@/lib/supabaseClient";

const Metric = ({ label, value, tone = "text-foreground" }) => <div className="rounded-xl border border-border bg-card p-4"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className={`mt-1 text-2xl font-bold ${tone}`}>{value}</p></div>;

export default function OperationsHealth({ orders = [] }) {
  const { data: events = [] } = useQuery({ queryKey: ["exec-team-activity"], queryFn: async () => { const { data, error } = await supabase.from("opps_activity_events").select("id, actor_email, actor_name, event_type, summary, created_at").order("created_at", { ascending: false }).limit(250); if (error) throw error; return data ?? []; } });
  const { data: reports = [] } = useQuery({ queryKey: ["exec-work-reports"], queryFn: async () => { const { data, error } = await supabase.from("opps_work_reports").select("id, user_email, user_name, role_key, report_type, blockers, submitted_at").order("submitted_at", { ascending: false }).limit(250); if (error) throw error; return data ?? []; } });
  const active = orders.filter((order) => !order.is_archived && !["delivered", "cancelled"].includes(order.status));
  const unowned = active.filter((order) => !order.assigned_to);
  const overdue = active.filter((order) => order.due_date && new Date(order.due_date) < new Date());
  const recentReports = reports.filter((report) => differenceInDays(new Date(), new Date(report.submitted_at)) <= 7);
  const members = useMemo(() => Object.values(events.reduce((acc, event) => { const key = event.actor_email || "unknown"; const entry = acc[key] || { email: key, name: event.actor_name || key, count: 0, latest: event.created_at, claims: 0, reports: 0 }; entry.count++; entry.latest = entry.latest > event.created_at ? entry.latest : event.created_at; if (event.event_type === "work_claimed") entry.claims++; if (event.event_type?.includes("report")) entry.reports++; acc[key] = entry; return acc; }, {})).sort((a, b) => b.count - a.count), [events]);
  const blockers = reports.filter((report) => report.blockers?.trim()).slice(0, 8);
  return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Active orders" value={active.length} /><Metric label="Without an owner" value={unowned.length} tone={unowned.length ? "text-amber-600" : "text-emerald-600"} /><Metric label="Overdue orders" value={overdue.length} tone={overdue.length ? "text-red-600" : "text-emerald-600"} /><Metric label="Reports this week" value={recentReports.length} /></div><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-card p-5"><h2 className="text-sm font-semibold text-foreground">Team activity</h2><p className="mb-3 text-xs text-muted-foreground">Work evidence from claims, acknowledgements and submitted reports.</p>{members.length ? <div className="space-y-2">{members.slice(0, 8).map((member) => <div key={member.email} className="flex items-center justify-between rounded-xl bg-secondary/40 px-3 py-2"><div><p className="text-sm font-medium">{member.name}</p><p className="text-xs text-muted-foreground">{member.claims} claims · {member.reports} reports</p></div><p className="text-xs text-muted-foreground">{formatDistanceToNow(new Date(member.latest), { addSuffix: true })}</p></div>)}</div> : <p className="text-sm text-muted-foreground">No activity recorded yet.</p>}</section><section className="rounded-2xl border border-border bg-card p-5"><h2 className="text-sm font-semibold text-foreground">Reported blockers</h2><p className="mb-3 text-xs text-muted-foreground">What the team says is slowing delivery right now.</p>{blockers.length ? <div className="space-y-2">{blockers.map((report) => <div key={report.id} className="rounded-xl border border-amber-100 bg-amber-50 p-3"><p className="text-xs font-semibold text-amber-900">{report.user_name || report.user_email} · {report.role_key || "team"}</p><p className="mt-1 text-sm text-amber-950">{report.blockers}</p></div>)}</div> : <p className="text-sm text-muted-foreground">No blockers reported in recent check-ins.</p>}</section></div><section className="rounded-2xl border border-border bg-card p-5"><h2 className="text-sm font-semibold text-foreground">Recent workflow history</h2><p className="mb-3 text-xs text-muted-foreground">A plain-language trail of operational changes.</p><div className="space-y-2">{events.slice(0, 12).map((event) => <div key={event.id} className="flex items-start justify-between gap-3 border-b border-border py-2 last:border-0"><p className="text-sm">{event.summary}</p><p className="whitespace-nowrap text-xs text-muted-foreground">{formatDistanceToNow(new Date(event.created_at), { addSuffix: true })}</p></div>)}</div></section></div>;
}